FROM node:20-bookworm

RUN apt-get update && apt-get install -y \
    openjdk-17-jre \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY processor/target/videoprocessor-jar-with-dependencies.jar /app/videoprocessor.jar

RUN mkdir -p /videos /results

WORKDIR /app/server
COPY server/package*.json ./
RUN npm install --silent
COPY server/ ./

#Create jobs & archive INSIDE the server folder
RUN mkdir -p /app/server/jobs /app/server/archive

ENV NODE_ENV=production
ENV VIDEOS=/videos
ENV OUTPUT_PATH=/results
ENV JOB=jobs
ENV ARCHIVE=archive
ENV TARGET=/app/videoprocessor.jar

EXPOSE 3000
CMD ["npm", "start"]