name: JUnit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Compile
        run: |
          mkdir -p src
          javac -cp lib/junit-platform-console-standalone-1.12.0.jar src/*.java

      - name: Run and Verify Tests
        run: |
          # Ensure that the pipeline fails if any command fails.
          set -o pipefail
          # Run tests and tee output to both the console and a file.
          java -jar lib/junit-platform-console-standalone-1.12.0.jar -cp src --scan-classpath | tee test-results.txt
          # Capture the exit code of the java command.
          exit_code=${PIPESTATUS[0]}
          if [ $exit_code -ne 0 ]; then
            echo "❌ Unit tests failed with exit code $exit_code."
            exit $exit_code
          fi

          # Extract the number of tests run from the output.
          TEST_COUNT=$(grep -oP '\d+(?= tests found)' test-results.txt | head -n 1)
          MIN_TESTS=15

          if [ "$TEST_COUNT" -lt "$MIN_TESTS" ]; then
            echo "❌ Only $TEST_COUNT tests were run. At least $MIN_TESTS tests are required. Please write more unit tests"
            exit 1
          fi

          echo "✅ All unit tests passed and $TEST_COUNT tests were executed."
